from .resnet_vlbert_for_pretraining_multitask import ResNetVLBERTForPretrainingMultitask
from .resnet_vlbert_for_pretraining_multitask2018 import ResNetVLBERTForPretrainingMultitask2018
from .resnet_vlbert_for_pretraining_multitask_no_vision import ResNetVLBERTForPretrainingMultitaskNoVision
from .resnet_vlbert_for_pretraining_multitask2018_no_vision import ResNetVLBERTForPretrainingMultitask2018NoVision


