from .resnet_vlbert_for_pretraining import ResNetVLBERTForPretraining
from .resnet_vlbert_for_pretraining_generate import ResNetVLBERTForPretrainingGenerate
from .resnet_vlbert_for_pretraining_multitask import ResNetVLBERTForPretrainingMultitask
from .resnet_vlbert_for_attention_vis import ResNetVLBERTForAttentionVis
from .resnet_vlbert_for_pretraining_taskC import ResNetVLBERTForPretrainingTaskC


