from .resnet_vlbert_for_pretraining import ResNetVLBERTForPretraining
from .resnet_vlbert_for_pretraining_multitask import ResNetVLBERTForPretrainingMultitask
from .resnet_vlbert_for_pretraining_encdec import ResNetVLBERTForPretrainingEncDec
from .resnet_vlbert_for_pretraining_encdec_generate import ResNetVLBERTForPretrainingEncDecGenerate
from .resnet_vlbert_for_pretraining_no_vision import ResNetVLBERTForPretrainingNoVision
from .resnet_vlbert_for_pretraining_generate import ResNetVLBERTForPretrainingGenerate
from .resnet_vlbert_for_pretraining_generate_no_vision import ResNetVLBERTForPretrainingGenerateNoVision
from .resnet_vlbert_for_pretraining_generate_image_only import ResNetVLBERTForPretrainingGenerateImageOnly
from .resnet_vlbert_for_pretraining_global_generate_image_only import ResNetVLBERTForPretrainingGlobalGenerateImageOnly
from .resnet_vlbert_for_pretraining_global_generate import ResNetVLBERTForPretrainingGlobalGenerate
from .resnet_vlbert_for_pretraining_global_generate_no_vision import ResNetVLBERTForPretrainingGlobalGenerateNoVision


