from .resnet_vlbert_for_pretraining import ResNetVLBERTForPretraining
from .resnet_vlbert_for_pretraining_multitask import ResNetVLBERTForPretrainingMultitask
from .resnet_vlbert_for_pretraining_translation_no_vision import ResNetVLBERTForPretrainingTranslationNoVision
from .resnet_vlbert_for_distance_translation_no_vision import ResNetVLBERTDistanceTranslationNoVision
from .resnet_vlbert_for_distance_translation_with_vision import ResNetVLBERTDistanceTranslationWithVision
from .resnet_vlbert_for_attention_vis import ResNetVLBERTForAttentionVis


